### ISSUE TITLE
Add C language example file.

### ISSUE THREAD

**Issue by Anjan50** [Anjan50/C-language#1]
C language file Add in C-language folder 
You can add any C language file and Project which you have practiced

example:
1. bubble-sort.c
2. ATM machine system.c
3 .tic tac toe.c

# You can Help of online learning website

1. Hello World Program in C
2. C program to check whether the given number is positive or negative
3. Reverse an input number using recursion
4. Program to find greatest of three numbers
5. C Program to print Fibonacci series in a given range
6. C Program to find factorial of a given number
7. Find Prime numbers in a given range
8. C Program to check if given number is Armstrong or not
9. C Program to check if given number is palindrome or not
10. C program to display palindrome numbers in a given range
11. C Program to check if number is odd or even
12. C Program to find out the ASCII value of a character
13. C Program to find the size of int, float, double and char
14. C Program to check whether an alphabet is vowel or consonant
15. C Program to check leap year
16. C Program to find sum of first n natural numbers

String Programs
1. Program to convert string from upper case to lower case
2. Program to convert string from lower case to upper case
3. Sort a set of strings in ascending alphabetical order
4. Find length of a string without using strlen()
5. String concatenation without using strcat
6. Reverse a String using recursion

Array Programs
1. Program to sort array in ascending order
2. Find largest element of given array
3. C program to find sum of array elements
4. C Program to find number of elements in an array

**Comment by thefool76** [comment]
hey anjan , how can i make pull req on this issue for yours? i am new t github and want to participate in hacktober fest and btw have you dint your 4 req?  if yes can u guide me btw i am  new

**Comment by Kishan-Sahu** [comment]
can you assign 11 number problem to me

**Comment by thefool76** [comment]
@Kishan-Sahu hey mate doing it for hacktoberfest? can you guide me

**Comment by Kishan-Sahu** [comment]
> @Kishan-Sahu hey mate doing it for hacktoberfest? can you guide me

what kind of help?

**Comment by thefool76** [comment]
how can i make my 4 full req on which repo?

**Comment by thefool76** [comment]
btw man pull req u have done? it now

**Comment by MaxJaycee** [comment]
Hey @Anjan50 can you assign me the Ascending Array.

**Comment by Anjan50** [comment]
> @thefool76 you can learn some basic concept from Google

**Comment by MohdImran001** [comment]
I'd love to add this program "Reverse an input number using recursion". To which issue I should make a PR.

**Comment by Anjan50** [comment]
Closed
